### ISSUE TITLE
Error running the code.

### ISSUE THREAD

**Issue by pinakiweb** [AlvaroCavalcante/auto_annotate#16]
I have successfully completed all the steps till running detection_images.py, but I encounter an error while running the script.
The below is the error I encountered. Do you know what's wrong? Thanks in advance

2021-06-16 10:11:51.834111: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Error parsing message

**Comment by AlvaroCavalcante** [comment]
Hello @pinakiweb, I never got an error like this before, what is your tensorflow version? Do you already run any object detection projects using the TensorFlow API before in your machine? Configuring this for the first time is a little hard.

**Comment by pinakiweb** [comment]
> Hello @pinakiweb, I never got an error like this before, what is your tensorflow version? Do you already run any object detection projects using the TensorFlow API before in your machine? Configuring this for the first time is a little hard.

Yes. I have trained a custom object detection model and wanted to automate the process for that. I have a .ckpt files and .pb file which is the saved model. I am using tensorflow 2.5.0. Is this the problem? Also I found out that the line below from detecting_images.py is giving the error.

od_graph_def.ParseFromString(serialized_graph)

Is this because of tensorflow version?

**Comment by pinakiweb** [comment]
Hey! Thanks I actually find out the problem. Great stuff by the way. It really helped me solve what I was looking for.

**Comment by AlvaroCavalcante** [comment]
@pinakiweb lol, I was just writing a response right now! I'm glad that you found the solution and that the tool was useful for you! If you have some improvement or suggestions, let me know!

**Comment by hassaanamer** [comment]
> Hey! Thanks I actually find out the problem. Great stuff by the way. It really helped me solve what I was looking for.

Hi, I have the same error, what was your solution?
