### ISSUE TITLE
xml files are not getting created 

### ISSUE THREAD

**Issue by kshamap** [AlvaroCavalcante/auto_annotate#2]
on running the script , xml images are not created but there is properly annotated jpg files in results folder. Any idea why this is happening?

Need Help

Thanks

**Comment by AlvaroCavalcante** [comment]
Hello @kshamap which TensorFlow version are you using? Did you get any error or warning message?

**Comment by AlvaroCavalcante** [comment]
Issue closed due to inactivity.

**Comment by DeepakShanthaiah** [comment]
On running detection_images.py script ,xml files are not been created but I can see the annotated images in result folder.
Tensorflow version I am using is 1.14.
I didn't get any error nor any warning.

Please let me know how to generate the XML files now as it is whole point of doing auto annotation @AlvaroCavalcante
