### ISSUE TITLE
Error parsing message

### ISSUE THREAD

**Issue by hassaanamer** [AlvaroCavalcante/auto_annotate#28]
Error:
od_graph_def.ParseFromString(serialized_graph)
google.protobuf.message.DecodeError: Error parsing message

Tensorflow version ==2.0.0

The issue remains consistent with all versions of tensorflow 2.he 

I have tested it models trained and frozen by google as well. 

    detection_graph = tf.Graph()
    with detection_graph.as_default():
        od_graph_def = tf.GraphDef()
        with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
            serialized_graph = fid.read()
            od_graph_def.ParseFromString(serialized_graph) --------------------------------- error
            tf.import_graph_def(od_graph_def, name='')

I have tried all the possible solutions I found online. It seems to be a common issue.

**Comment by hassaanamer** [comment]
It works with tensorflow 1.14. I was under the impression for some reason it had been updated to be made compatible with tensorflow 2. If you finetune a model from tf1 model zoo on your custom dataset using tf 1 and then use it with this repository it works. Finetuning a model from tf2 model zoo and then exporting it, is not supported.

@AlvaroCavalcante please correct me if this is incorrect.

**Comment by AlvaroCavalcante** [comment]
@hassaanamer thank you for all your debugging on the project, it's very useful! I'll work on a version that is fully compatible with TF 2.x ok? It'll be released soon :)

**Comment by AlvaroCavalcante** [comment]
Hello @hassaanamer , I just finished the new version of auto annotation for TF 2.x. To try to use it, please, run the detection_img_tf2.py file inside scripts. To run this file you need this command:

```
python3 scripts/detection_img_tf2.py --saved_model /path-saved-model --labelmap /path-label-map.pbtxt --imgs /path-of-the-imgs
```
Please, let me know if everything worked as expected!

**Comment by hassaanamer** [comment]
Hi @AlvaroCavalcante I tested it with ssd_mobilenet_v2_320x320_coco17_tpu-8 using tensorflow version  2.6.0. Everything works as expected. Thanks!

**Comment by AlvaroCavalcante** [comment]
That's great @hassaanamer, I'll now close this issue then! :)
