### ISSUE TITLE
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

### ISSUE THREAD

**Issue by prism5426** [AlvaroCavalcante/auto_annotate#36]
I am using tf2.5 and fixed other parsing issues in Windows, but now I came across this which I have no idea how to resolve it. Thanks!
![image](https://user-images.githubusercontent.com/64817770/128656546-ac80e99b-dfd9-4bef-b1fe-87007fa1c416.png)

**Comment by AlvaroCavalcante** [comment]
Hello @prism5426, I just finished the new version of auto annotation for TF 2.x. To try to use it, please, run the detection_img_tf2.py file inside scripts. To run this file you need this command:

```
python3 scripts/detection_img_tf2.py --saved_model /path-saved-model --labelmap /path-label-map.pbtxt --imgs /path-of-the-imgs
```
Please, let me know if everything worked as expected!

**Comment by shabbir9916** [comment]
Hello @AlvaroCavalcante I tried to run this comand  "python3 scripts/detection_img_tf2.py --saved_model /path-saved-model --labelmap /path-label-map.pbtxt --imgs /path-of-the-imgs" but I found this issue

![Screenshot 2021-08-20 120639](https://user-images.githubusercontent.com/80184839/130190960-724f0ecd-ddf6-474b-b88c-fd96bd218926.png)

**Comment by AlvaroCavalcante** [comment]
Hello @shabbir9916, as mentioned in the auto annotation tutorial [here](https://medium.com/analytics-vidhya/auto-annotate-images-for-tensorflow-object-detection-19b59f31c4d9), you need to replace the content of the visualization_utils.py to add the lines of code needed to the project work correctly. This file is inside the TF garden repo, in models/research/object_detection/utils. An easy way to do this is to copy all the content in the "visualization_utils_v2.py" in this repo and paste it into the visualization_utils.py of the TF repo. Let me know if you have any doubt, I recommend checking the mentioned tutorial to get a cleaner idea.

**Comment by AlvaroCavalcante** [comment]
@shabbir9916 I'll close this issue due to inactivity. Please, feel free to reopen if you have some news!
