### ISSUE TITLE
XML result path dynamically

### ISSUE THREAD

**Issue by AlvaroCavalcante** [AlvaroCavalcante/auto_annotate#38]
When using the auto annotate tool, mainly in version 2.x of the TF, we could pass all the arguments dynamically on the command line! The problem is that the **generate_xml.py** file still has a hardcoded path that needs to be replaced with a dynamic option, as saw in the line below:
```
arquivo.write('your-local-path-here/xml/' + self.file_name + '.xml')
```
The idea of this issue is to create a new argument on the file **detection_img_tf2.py** that contains the XML path that the user wants to get the results. 

The argument must be passed to the **generate_xml.py** and the XML results must appear in the folder specified in the arguments when calling the execution command!

**Comment by Apidwalinz** [comment]
[readme.md](https://github.com/AlvaroCavalcante/auto_annotate/files/7605722/readme.md)

**Comment by AlvaroCavalcante** [comment]
I'm closing this issue as it'll not be necessary anymore in the new version of the library!
