### ISSUE TITLE
XML generated are distorted when opened in LabelImg annotation tool 

### ISSUE THREAD

**Issue by DeepakShanthaiah** [AlvaroCavalcante/auto_annotate#5]
Hello @AlvaroCavalcante , Thanks for your previous responses. I have encountered new problem i.e, after generating the XML files when I try to open the folder which has image and its xml file in LabelImg tool ,I can see the bounding boxes with right co-ordinates but it is not annotated on the right part it is distorted in the image.

Example : if there are classes A,B,C I can see three bounding boxes when I open in LabelImg tool but all those 3 boxes are not annotated on the particular part . It is like bounding boxes are drawn but not on that particular part. 

So this makes life tough again re-arranging the boxes by checking which class does the box belongs to .

I will be glad if you can help me resolve this issue , so I can post all the new changes that I did to get the better results which will help others who are facing same issues.

**Comment by AlvaroCavalcante** [comment]
@DeepakShanthaiah I already had this problem, but I thought that was fixed. This is probably happening because the proportion of the image is not the same as the XML in the generation process. To confirm this hypothesis, check your output JPG file, the generated bounding boxes are in the correct positions? 

Your problem may be here:
https://github.com/AlvaroCavalcante/auto_annotate/blob/d08e728047ba3374bd414f7d2427746811687895/scripts/visualization_utils.py#L858

In this line of code, the bounding box position is set, but if for some reason your im_width/height is not correct, the proportion of the box will not be correct. 

Please, let me know about your findings!

**Comment by DeepakShanthaiah** [comment]
Hello @AlvaroCavalcante ,The result folder where I get the output image in that the bounding boxes are exactly on the part. Also, the co-ordinates of the bounding boxes fits exactly when I drag that bounding box on the particular part in LabelImg tool and this is tedious task to drag and place that bounding boxes everytime for multiple class.If it gets auto annotated on the part itself if not 100% atleast 90% of that part it will help us .

I did went through that line and I am not able to figure out why is this issue.

If the bounding boxes in output jpg image is perfect then why is it generating XML file with distorted localization of annotation. I guess something is going wrong while writing XML file.

Any alternative suggestion you can help me with to tackle this ?

**Comment by DeepakShanthaiah** [comment]
@AlvaroCavalcante , I just tried checking the proportion of image: 
In my input image : width =640 and height =480 
In Xml file which is generated the width and height are same as above but the output image in result folder has width =636 and height = 482, so here is the issue I believe. What should I do to overcome this  ?

**Comment by AlvaroCavalcante** [comment]
@DeepakShanthaiah don't worry, we'll solve your problem! Well, I've done the following test: 
- I got an online image of a leaf disease (my object detection model is trained for it) and resized with the same resolution as your image (640 x 480):
![Webp net-resizeimage](https://user-images.githubusercontent.com/37350513/100948655-22bf8a80-34e7-11eb-9365-7f1964348c02.jpg)
- After that, I ran the script and got the following JPG output:
![image_1](https://user-images.githubusercontent.com/37350513/100948773-64e8cc00-34e7-11eb-9d04-b2b64cc9c99c.jpg)
- I copied and pasted the generated XML file in the same folder as my original image (without detections). 
- Then I opened the LabelImage software, and clicked on "Open Dir", selecting my directory with my image and XML. 
- The result is the bounding box in the right position, as saw in the output JPG.

**Important detail** - please, note that your XML and JPG MUST have the same name, not only in the file but inside the <filename> tag in XML, here is my working example:
 
![image](https://user-images.githubusercontent.com/37350513/100949048-1f78ce80-34e8-11eb-807e-ac9e8cd537af.png)

And inside the XML file:
![image](https://user-images.githubusercontent.com/37350513/100949069-2ef81780-34e8-11eb-8953-7276a012157f.png)

If you have trouble with the file name, let me know, I already implemented a solution to solve this, passing the same name to the image and XML file inside generate_xlm class.

**Comment by AlvaroCavalcante** [comment]
@DeepakShanthaiah I've added an update on branch master to get the XML name automatically based on the JPG filename.

**Comment by DeepakShanthaiah** [comment]
Hello @AlvaroCavalcante , Thanks for your response . The issue is resolved and it helped me reduce my time in annotating.

**Comment by AlvaroCavalcante** [comment]
@DeepakShanthaiah Good news! If you have any other problems, feel free to report. I'll close this issue now.
