### ISSUE TITLE
Version issue within the setup.py

### ISSUE THREAD

**Issue by nkulkarni3297** [AlvaroCavalcante/auto_annotate#52]
Hello, I am trying to install the auto_annotate with pip as you have recommended. But as per your setup.py file, Pillow=7.0.0 version is recommended but while installation of auto_annotate through pip, it shows the following error

![image](https://user-images.githubusercontent.com/78587643/193274097-12879356-ec8a-4cd2-9344-b04fc4920cd9.png)

I tried to separately install Pillow 7.0.0 version but still not able to downgrade from 9.2 to 7.0. I also saw 1 pull request for the same. Is it possible for you to pull the requests for the versions as few older versions are not being able to downgrade.

**Comment by AlvaroCavalcante** [comment]
Hello @nkulkarni3297, great to know, I didn't notice that bug before! 

I'll try to update the project dependencies in the next few days, but meanwhile, you could try to initialize a new virtual environment (without previous dependencies) and install auto-annotate in this new environment, which will probably work.

**Comment by nkulkarni3297** [comment]
Well currently, I am using your older version of auto_annotate, where we used detection_image_tf2.py file and sort of files which is currently working fine for me, but you definitely make this dependencies workout with the updated versions. 

Thank you....

**Comment by faisalahmadnf** [comment]
> Hello @nkulkarni3297, great to know, I didn't notice that bug before!
> 
> I'll try to update the project dependencies in the next few days, but meanwhile, you could try to initialize a new virtual environment (without previous dependencies) and install auto-annotate in this new environment, which will probably work.

Hello, do you have tutorial for this? i'm very need this step

**Comment by nkulkarni3297** [comment]
@faisalahmadnf you can follow the article published by @AlvaroCavalcante which you can find on the code page under how it works.

**Comment by faisalahmadnf** [comment]
> @faisalahmadnf you can follow the article published by @AlvaroCavalcante which you can find on the code page under how it works.

I have tried, but I get an error like you . can you help me sir?

**Comment by nkulkarni3297** [comment]
@faisalahmadnf if you are facing version issues, you can shift to the older version of auto_ml which worked adequately for me. Please feel free to email me if you'd like to work with that version. I'll try to share that with you with the prior approval from @AlvaroCavalcante

**Comment by faisalahmadnf** [comment]
> @faisalahmadnf if you are facing version issues, you can shift to the older version of auto_annotate which worked adequately for me. Please feel free to email me if you'd like to work with that version. I'll try to share that with you with the prior approval from @AlvaroCavalcante

thankyou, this is my email fanf1910@gmail.com

**Comment by faisalahmadnf** [comment]
> @faisalahmadnf if you are facing version issues, you can shift to the older version of auto_annotate which worked adequately for me. Please feel free to email me if you'd like to work with that version. I'll try to share that with you with the prior approval from @AlvaroCavalcante

ok, can you send to my email? this is my adress fanf1910@gmail.com

**Comment by AlvaroCavalcante** [comment]
Hello @faisalahmadnf, I sent you an e-mail, I'll be happy to help you to use the project :)

**Comment by nkulkarni3297** [comment]
@AlvaroCavalcante Have you tried resolving the version issues in this?

**Comment by AlvaroCavalcante** [comment]
@nkulkarni3297 and @faisalahmadnf, I have just published a new version of auto-annotate upgrading the libraries version. Currently, this package is just supported for python >= 3.8, but it seems that there are no more dependencies issues! 

I'm create a collab notebook showing the installation and use of the library in more details. Let me know if everything is working now!

**Comment by faisalahmadnf** [comment]
> @nkulkarni3297 and @faisalahmadnf, I have just published a new version of auto-annotate upgrading the libraries version. Currently, this package is just supported for python >= 3.8, but it seems that there are no more dependencies issues!
> 
![Screenshot_20230110_091932](https://user-images.githubusercontent.com/114332587/211447397-ef2af79a-d39c-49f6-97aa-3738da7725c5.png)

**Comment by nkulkarni3297** [comment]
@faisalahmadnf I would recommend you to change your pbtxt file name from label_map.pbtxt to saved_model.pbtxt and then I think it should work

**Comment by faisalahmadnf** [comment]
> @faisalahmadnf First and foremost thing you are getting the error because your path for pbtxt file is different from the path of your pb file. Keep both the files in the same folder, in your case `/example/saved_model/` and I would also recommend you to change your pbtxt file name from label_map.pbtxt to saved_model.pbtxt and then I think it should work.

not work for me, still appears as above

**Comment by nkulkarni3297** [comment]
@faisalahmadnf try removing all such dependencies by manually installing packages and then try to run the function again

**Comment by nkulkarni3297** [comment]
try code in this manner `ann_tool = AutoAnnotate(
              saved_model_path = '/example/saved_model',
              label_map_path = '/example/saved_model.pbtxt',
              images_path = '/example/dataset_images',
              xml_path = '/example/dataset_labels',
              detection_threshold = 0.65)`
but you mistakenly passed the .pb file directly.

**Comment by AlvaroCavalcante** [comment]
As I told you by e-mail @faisalahmadnf, this is possibly a problem with your library version. Please, install the latest version to fix this:

```pip install auto-annotate==1.0.4```

**Comment by AlvaroCavalcante** [comment]
Hello guys, 

Actually, the correct version of auto-annotate is 1.0.5, so you need to install using the following command:

```pip install auto-annotate==1.0.5```

Besides that, I made an example Google Colab showing how to use the library: https://colab.research.google.com/drive/14qgA9IUYCVAALJmJabvQ9sDxrKxEezwP?usp=sharing

If you have any questions, please let me know.

**Comment by faisalahmadnf** [comment]
> Hello guys,
> 
> Actually, the correct version of auto-annotate is 1.0.5, so you need to install using the following command:
> 
> `pip install auto-annotate==1.0.5`
> 
> Besides that, I made an example Google Colab showing how to use the library: https://colab.research.google.com/drive/14qgA9IUYCVAALJmJabvQ9sDxrKxEezwP?usp=sharing
> 
> If you have any questions, please let me know.

@AlvaroCavalcante and @nkulkarni3297 Hello, I want to say thank you guys, finally this project can work fine for me

**Comment by AlvaroCavalcante** [comment]
Great to hear this @faisalahmadnf, I'll close this issue now, let me know with you have more problems using the project.
