### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by Lucs1590** [AlvaroCavalcante/auto_annotate#62]
An excellent option to provide agility to users is to create an issue template for each kind of area.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

My proposal in this issue is related to creating issue templates to:
 - Bug Report;
 - Feature Request.

**Comment by Lucs1590** [comment]
I've implemented it at  #63 !

**Comment by AlvaroCavalcante** [comment]
Thank you @Lucs1590, I have merged the PR!
