### ISSUE TITLE
using yolov5 model

### ISSUE THREAD

**Issue by SJavad** [AlvaroCavalcante/auto_annotate#70]
Can I use this method for labeling data set for yolov5 model ? 
I have very large data set for yolov5 model for object detection

**Comment by AlvaroCavalcante** [comment]
Hello @SJavad, how are you?

The project itself was designed for TensorFlow models, and it generates PASCAL VOC (.xml) labels. However, once you have PASCAL VOC labels, it is pretty easy to convert them into Yolo format (.txt).

Here is a simple article showing how to convert the annotations from one format to another: https://towardsdatascience.com/convert-pascal-voc-xml-to-yolo-for-object-detection-f969811ccba5.

So, my recommendation to you would be to train your initial model using TensorFlow and to create your annotations using this project, making it easy and faster to label your large-scale dataset. After that, you just need to convert your annotations from xml to txt and train your final model, which is the yolov5.

I did the same thing in one of my last works related to object detection and I had no problem converting the annotations and training my YoloV7 model!

Best Regards.
